
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AsadAli
 */
public class F10 extends javax.swing.JFrame {

    /**
     * Creates new form F10
     */
    public F10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtDate = new javax.swing.JTextField();
        lblComplaintID = new javax.swing.JLabel();
        txtComplaintID = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnStatus = new javax.swing.JLabel();
        boxStatus = new javax.swing.JComboBox<>();
        btnUpdate1 = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Compliants Status ");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 44, 280, 50));

        btnSearch.setBackground(new java.awt.Color(204, 204, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 143, 150, 40));

        txtDate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 471, 180, 30));

        lblComplaintID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblComplaintID.setText("Complaint ID ");
        getContentPane().add(lblComplaintID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 180, 30));

        txtComplaintID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtComplaintID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplaintIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtComplaintID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 180, 30));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUsername.setText("User Name");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 180, 30));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 180, 30));

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCategory.setText("Category");
        getContentPane().add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 331, 180, 30));

        txtCategory.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtCategory.setToolTipText("");
        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 331, 180, 30));

        lblDescription.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDescription.setText("Description");
        getContentPane().add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 400, 180, 30));

        txtDescription.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 400, 180, 30));

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDate.setText("Date");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 471, 180, 30));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 143, 180, 30));

        btnStatus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnStatus.setText("Status");
        getContentPane().add(btnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 532, 180, 30));

        boxStatus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        boxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Working", "Reslvoed", " " }));
        boxStatus.setToolTipText("");
        getContentPane().add(boxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 532, 180, 30));

        btnUpdate1.setBackground(new java.awt.Color(204, 204, 255));
        btnUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate1.setText("Update");
        btnUpdate1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 627, 150, 40));

        btnBack1.setBackground(new java.awt.Color(204, 204, 255));
        btnBack1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 628, 150, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("City");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 180, 34));

        txtcity.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        getContentPane().add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 178, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/status.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
  // 1) Read search input (trim)
    String idText = txtSearch.getText().trim();

    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Complaint ID in the search field first.");
        return;
    }

    int id;
    try {
        id = Integer.parseInt(idText);
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Complaint ID must be a number.");
        return;
    }

    // 2) DB fetch
    java.sql.Connection con = null;
    java.sql.PreparedStatement pst = null;
    java.sql.ResultSet rs = null;
    try {
        con = database.DBConnection.getConnection(); // use your DBConnection
        String sql = "SELECT * FROM complaints WHERE complaint_id = ?";
        pst = con.prepareStatement(sql);
        pst.setInt(1, id);
        rs = pst.executeQuery();

        if (rs.next()) {
            // Fill UI fields with values from DB
            txtComplaintID.setText(String.valueOf(rs.getInt("complaint_id"))); // optional (read-only)
            txtUsername.setText(rs.getString("name"));
            txtcity.setText(rs.getString("city"));
            txtCategory.setText(rs.getString("category"));
            txtDescription.setText(rs.getString("description"));
            // date field: if stored as DATE or TIMESTAMP, use toString or format
            txtDate.setText(rs.getString("date"));
            // set combo selection safely
            String status = rs.getString("status");
            if (status != null) boxStatus.setSelectedItem(status);
            else boxStatus.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Complaint ID not found.");
            // optional: clear fields
            // clearFields();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    } finally {
        try { if (rs != null) rs.close(); } catch (Exception ex) {}
        try { if (pst != null) pst.close(); } catch (Exception ex) {}
        // don't close shared connection if DBConnection manages it; otherwise close:
        // try { if (con != null) con.close(); } catch (Exception ex) {}
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        txtDate.setEditable(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtComplaintIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplaintIDActionPerformed
        txtComplaintID.setEditable(false);   // TODO add your handling code here:
    }//GEN-LAST:event_txtComplaintIDActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        txtUsername.setEditable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        txtCategory.setEditable(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        txtDescription.setEditable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed

    this.dispose();

    // F7 (Staff Dashboard) open karne ke liye
    F7 dashboard = new F7();
    dashboard.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
                                        
     String idText = txtComplaintID.getText().trim();
    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please search and load a complaint first (Complaint ID empty).");
        return;
    }

    int id;
    try {
        id = Integer.parseInt(idText);
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Invalid Complaint ID.");
        return;
    }

    String newStatus = boxStatus.getSelectedItem() == null ? "" : boxStatus.getSelectedItem().toString();

    if (newStatus.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a status.");
        return;
    }

    java.sql.Connection con = null;
    java.sql.PreparedStatement pst = null;
    try {
        con = database.DBConnection.getConnection();
        String sql = "UPDATE complaints SET status = ? WHERE complaint_id = ?";
        pst = con.prepareStatement(sql);
        pst.setString(1, newStatus);
        pst.setInt(2, id);

        int rows = pst.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Status updated successfully.");
            // optional: reload the record to reflect any DB-side changes:
            // btnSearchActionPerformed(null); // call search code or write a reload method
        } else {
            JOptionPane.showMessageDialog(this, "Update failed: Complaint ID not found.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    } finally {
        try { if (pst != null) pst.close(); } catch (Exception ex) {}
        // maybe don't close shared connection
    }
 

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxStatus;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel btnStatus;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblComplaintID;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtComplaintID;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtcity;
    // End of variables declaration//GEN-END:variables
}
