


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AsadAli
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class F3 extends javax.swing.JFrame {

    /**
     * Creates new form F3
     */
    public F3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistration = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblFather = new javax.swing.JLabel();
        lblMobileno = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblconfirmpassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtfathersname = new javax.swing.JTextField();
        txtmobileno = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        fldpassword = new javax.swing.JPasswordField();
        fldconfirmpasswod = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        boxusers = new javax.swing.JComboBox<>();
        lblusertype = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration ");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistration.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblRegistration.setForeground(new java.awt.Color(0, 51, 102));
        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setText("User Registration Form");
        getContentPane().add(lblRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 520, 60));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 51, 102));
        lblName.setText("Full Name");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 300, 35));

        lblFather.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblFather.setForeground(new java.awt.Color(0, 51, 102));
        lblFather.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFather.setText("Father's Name");
        getContentPane().add(lblFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 300, 35));

        lblMobileno.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMobileno.setForeground(new java.awt.Color(0, 51, 102));
        lblMobileno.setText("Mobile No");
        getContentPane().add(lblMobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 300, 35));

        lblcity.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblcity.setForeground(new java.awt.Color(0, 51, 102));
        lblcity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblcity.setText("City");
        getContentPane().add(lblcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 300, 35));

        lblemail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblemail.setForeground(new java.awt.Color(0, 51, 102));
        lblemail.setText("Email");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 300, 35));

        lblpassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(0, 51, 102));
        lblpassword.setText("Password");
        getContentPane().add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 300, 35));

        lblconfirmpassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblconfirmpassword.setForeground(new java.awt.Color(0, 51, 102));
        lblconfirmpassword.setText("Confirm Password");
        getContentPane().add(lblconfirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 300, 35));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 51, 102));
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 300, 30));

        txtfathersname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtfathersname.setForeground(new java.awt.Color(0, 51, 102));
        txtfathersname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        getContentPane().add(txtfathersname, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 300, 30));

        txtmobileno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtmobileno.setForeground(new java.awt.Color(0, 51, 102));
        txtmobileno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        getContentPane().add(txtmobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 300, 30));

        txtcity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcity.setForeground(new java.awt.Color(0, 51, 102));
        txtcity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        getContentPane().add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 300, 30));

        txtusername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(0, 51, 102));
        txtusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 300, 30));

        fldpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fldpassword.setForeground(new java.awt.Color(0, 51, 102));
        fldpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        getContentPane().add(fldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 300, 30));

        fldconfirmpasswod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fldconfirmpasswod.setForeground(new java.awt.Color(0, 51, 102));
        fldconfirmpasswod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        fldconfirmpasswod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldconfirmpasswodActionPerformed(evt);
            }
        });
        getContentPane().add(fldconfirmpasswod, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 300, 30));

        btnRegister.setBackground(new java.awt.Color(0, 123, 255));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, 150, 40));

        btnClear.setBackground(new java.awt.Color(0, 102, 255));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 620, 150, 40));

        boxusers.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        boxusers.setForeground(new java.awt.Color(0, 51, 102));
        boxusers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User ", "Staff", " " }));
        getContentPane().add(boxusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 527, 300, 42));

        lblusertype.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblusertype.setForeground(new java.awt.Color(0, 51, 102));
        lblusertype.setText("Register as");
        getContentPane().add(lblusertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 527, 276, 42));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/REGISTRATION.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fldconfirmpasswodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldconfirmpasswodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldconfirmpasswodActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

                                            
    String name = txtName.getText().trim();
    String father = txtfathersname.getText().trim();
    String city = txtcity.getText().trim();
    String mobile = txtmobileno.getText().trim();
    String username = txtusername.getText().trim();  // email ya username
    String password = new String(fldpassword.getPassword());
    String confirm = new String(fldconfirmpasswod.getPassword());
    String userType = boxusers.getSelectedItem().toString().trim();  // ComboBox se value le raha hai

    // Step 1: Validation
    if (name.isEmpty() || father.isEmpty() || city.isEmpty() || mobile.isEmpty() ||
        username.isEmpty() || password.isEmpty() || confirm.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields!");
        return;
    }

    if (!password.equals(confirm)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match!");
        return;
    }

    try {
        // Step 2: Database Connection
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/complaint_management", "root", "asad1234");

        // Step 3: Check if username already exists
        String checkQuery = "SELECT * FROM users WHERE Email = ?";
        PreparedStatement pst = con.prepareStatement(checkQuery);
        pst.setString(1, username);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Username already exists!");
            con.close();
            return;
        }

        // Step 4: Insert new record
        String insertQuery = "INSERT INTO users(name, father_name, city, mobile, Email, password, user_type) VALUES (?, ?, ?, ?, ?, ?, ?)";
        pst = con.prepareStatement(insertQuery);
        pst.setString(1, name);
        pst.setString(2, father);
        pst.setString(3, city);
        pst.setString(4, mobile);
        pst.setString(5, username);
        pst.setString(6, password);
        pst.setString(7, userType);

        int inserted = pst.executeUpdate();

        if (inserted > 0) {
            JOptionPane.showMessageDialog(this, "Registration Successful!");

            // ✅ Clear all fields
            txtName.setText("");
            txtfathersname.setText("");
            txtcity.setText("");
            txtmobileno.setText("");
            txtusername.setText("");
            fldpassword.setText("");
            fldconfirmpasswod.setText("");
            boxusers.setSelectedIndex(0);

            // ✅ Open dashboard based on user type
            if (userType.equalsIgnoreCase("User")) {
                new F4().setVisible(true); // replace F5 with your User dashboard frame name
            } else if (userType.equalsIgnoreCase("Staff")) {
                new F7().setVisible(true); // replace F7 with your Staff dashboard frame name
            }

            // Close current registration form
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Registration Failed!");
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
                                             
    txtName.setText("");
    txtfathersname.setText("");
    txtmobileno.setText("");
    txtcity.setText("");
    txtusername.setText("");
    fldpassword.setText("");
    fldconfirmpasswod.setText("");

    // Focus pehla field par wapas le jao (optional)
    txtName.requestFocus();



        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxusers;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPasswordField fldconfirmpasswod;
    private javax.swing.JPasswordField fldpassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFather;
    private javax.swing.JLabel lblMobileno;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblconfirmpassword;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusertype;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtfathersname;
    private javax.swing.JTextField txtmobileno;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
