
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AsadAli
 */
public class F4 extends javax.swing.JFrame {

    /**
     * Creates new form F4
     */
    public F4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblFooter = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setBackground(new java.awt.Color(102, 102, 102));
        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome to the Complaint Management System");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 770, 40));

        lblFooter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(255, 255, 255));
        lblFooter.setText("© 2025 Complaint Management System - All Rights Reserved");
        getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 660, 480, 30));

        btnRegister.setBackground(new java.awt.Color(211, 211, 211));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRegister.setText("Register Complaint");
        btnRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, 180, 40));

        btnView.setBackground(new java.awt.Color(211, 211, 211));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnView.setText("View Complaints");
        btnView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 180, 40));

        btnLogout.setBackground(new java.awt.Color(211, 211, 211));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 180, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userdashboard.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
btnRegister.setContentAreaFilled(false);
btnRegister.setOpaque(false);
btnRegister.setForeground(Color.WHITE);
        // TODO add your handling code here:
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnRegister.setForeground(Color.YELLOW);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        btnRegister.setForeground(Color.WHITE);
    }
});
                                                         
    F5 registerComplaint = new F5();   // F5 form ka object
    registerComplaint.setVisible(true); // Form show karo
    registerComplaint.pack();           // Layout adjust karo
    registerComplaint.setLocationRelativeTo(null); // Center me show karo
    this.dispose();                     // Current (F4) form close karo



    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
   btnView.setContentAreaFilled(false);
btnView.setOpaque(false);
btnView.setForeground(Color.WHITE);
        // TODO add your handling code here:
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnView.setForeground(Color.YELLOW);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        btnView.setForeground(Color.WHITE);
    }
}); 
                                                      
    F6 viewComplaints = new F6();       // F6 form ka object banao
    viewComplaints.setVisible(true);    // Form ko show karo
    viewComplaints.pack();              // Layout adjust karo
    viewComplaints.setLocationRelativeTo(null); // Center me open karo
    this.dispose();                     // Current (Dashboard) form close karo

// TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
            btnLogout.setContentAreaFilled(false);
btnLogout.setOpaque(false);
btnLogout.setForeground(Color.WHITE);
        // TODO add your handling code here:
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
       btnLogout.setForeground(Color.YELLOW);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
     btnLogout.setForeground(Color.WHITE);
    }
}); 
     F2 login = new F2();
    login.setVisible(true);

    // Current form (Dashboard) close karo
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
