/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AsadAli
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class F5 extends javax.swing.JFrame {

    /**
     * Creates new form F5
     */
    public F5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnSumbit = new javax.swing.JButton();
        boxItems = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 64, 128));
        lblID.setText("Complaint ID");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 250, 35));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 64, 128));
        lblName.setText("Name");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 250, 35));

        lblCity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 63, 128));
        lblCity.setText("City");
        getContentPane().add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 250, 35));

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(0, 64, 128));
        lblCategory.setText("Category");
        lblCategory.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 250, 35));

        lblDescription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(0, 64, 128));
        lblDescription.setText("Description");
        getContentPane().add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 250, 35));

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 64, 128));
        lblDate.setText("Date");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 250, 35));

        btnSumbit.setBackground(new java.awt.Color(204, 204, 204));
        btnSumbit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSumbit.setText("Sumbit");
        btnSumbit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSumbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumbitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSumbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 150, 40));

        boxItems.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boxItems.setForeground(new java.awt.Color(0, 51, 102));
        boxItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Water", " Electricity", " Road", "Garbage", " Others", " " }));
        boxItems.setToolTipText("");
        boxItems.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(boxItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 250, 35));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 51, 102));
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 250, 35));

        txtCity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCity.setForeground(new java.awt.Color(0, 51, 102));
        txtCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 250, 35));

        txtdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdate.setForeground(new java.awt.Color(0, 51, 102));
        txtdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 250, 35));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 51, 102));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        txtID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(0, 51, 102));
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 250, 35));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 150, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 64, 128));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register Your Complaint");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 36, 410, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rigeter Complain.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                                        
    // F4 = Dashboard Form
    F4 dashboard = new F4();
    dashboard.setVisible(true);
    dashboard.pack();
    dashboard.setLocationRelativeTo(null); // Center screen
    this.dispose(); // Current form (Register Complaint) band kar do

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSumbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumbitActionPerformed
                                            

    String name = txtName.getText().trim();
    String city = txtCity.getText().trim();
    String category = (String) boxItems.getSelectedItem(); // <-- correct
    if (category == null) category = "";
    String description =jTextArea1.getText().trim();
    String date =txtdate.getText().trim(); // format: yyyy-mm-dd

    if (name.isEmpty() || city.isEmpty() || category.isEmpty() || description.isEmpty() || date.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields!");
        return;
    }

    try {
        Connection con = database.DBConnection.getConnection();
        String sql = "INSERT INTO complaints (name, city, category, description, date) VALUES (?, ?, ?, ?, ?)";
       java.sql.PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, name);
        pst.setString(2, city);
        pst.setString(3, category);
        pst.setString(4, description);
        pst.setDate(5, java.sql.Date.valueOf(date)); // ensure date in yyyy-mm-dd
        int rows = pst.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Complaint submitted successfully!");
            // clear fields
            txtName.setText("");
            txtCity.setText("");
            boxItems.setSelectedIndex(0); // reset combo
            jTextArea1.setText("");
            txtdate.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to submit complaint!");
        }
        // pst.close(); con.close(); // optional
    } catch (IllegalArgumentException ie) {
        JOptionPane.showMessageDialog(this, "Date format incorrect. Use yyyy-mm-dd");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }



    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSumbitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxItems;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSumbit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtdate;
    // End of variables declaration//GEN-END:variables
}
