/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AsadAli
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class F6 extends javax.swing.JFrame {

    /**
     * Creates new form F6
     */
    public F6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblcategory = new javax.swing.JLabel();
        lblComplaints = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbldescription = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        txtcomplint = new javax.swing.JTextField();
        txtcategory = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tadescription = new javax.swing.JTextArea();
        txtdate = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("My Complaints");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        lblcategory.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblcategory.setText(" Category");
        getContentPane().add(lblcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 180, 30));

        lblComplaints.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblComplaints.setText(" Complaint ID");
        getContentPane().add(lblComplaints, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 180, 30));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblStatus.setText("Status");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 180, 30));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 180, 30));

        btnSearch.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 90, 160, 40));

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 160, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 250, 180, 30));

        lbldescription.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbldescription.setText("Description");
        getContentPane().add(lbldescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 280, 180, 30));

        lbldate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbldate.setText("Date");
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 395, 180, 30));

        txtcomplint.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        getContentPane().add(txtcomplint, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 180, 30));

        txtcategory.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        getContentPane().add(txtcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 237, 180, 30));

        tadescription.setColumns(20);
        tadescription.setRows(5);
        jScrollPane1.setViewportView(tadescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        txtdate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 395, 180, 30));

        txtstatus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        getContentPane().add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 461, 180, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Uerprofile.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                                      
    F4 userDashboard = new F4();   // Dashboard form ka object
    userDashboard.setVisible(true); // Show Dashboard
    userDashboard.pack();           // Layout adjust karo
    userDashboard.setLocationRelativeTo(null); // Center me open hoga
    this.dispose();                 // Current (View Complaint) form band hoga

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
      
        // TODO add your handling code here:
     
// 1) Read search input (trim)
    String idText = txtSearch.getText().trim();

    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Complaint ID in the search field first.");
        return;
    }

    int id;
    try {
        id = Integer.parseInt(idText);
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Complaint ID must be a number.");
        return;
    }

    // 2) DB fetch
    java.sql.Connection con = null;
    java.sql.PreparedStatement pst = null;
    java.sql.ResultSet rs = null;
    try {
        con = database.DBConnection.getConnection(); // use your DBConnection
        String sql = "SELECT * FROM complaints WHERE complaint_id = ?";
        pst = con.prepareStatement(sql);
        pst.setInt(1, id);
        rs = pst.executeQuery();

        if (rs.next()) {
            // Fill UI fields with values from DB
            txtcomplint.setText(String.valueOf(rs.getInt("complaint_id"))); // optional (read-only)
          
           
            txtcategory.setText(rs.getString("category"));
            tadescription.setText(rs.getString("description"));
            // date field: if stored as DATE or TIMESTAMP, use toString or format
            txtdate.setText(rs.getString("date"));
              txtstatus.setText(rs.getString("status"));
            // set combo selection safely
           
            JOptionPane.showMessageDialog(this, "Complaint ID found.");
            // optional: clear fields
            // clearFields();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    } finally {
        try { if (rs != null) rs.close(); } catch (Exception ex) {}
        try { if (pst != null) pst.close(); } catch (Exception ex) {}
        // don't close shared connection if DBConnection manages it; otherwise close:
        // try { if (con != null) con.close(); } catch (Exception ex) {}
    }

    


    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComplaints;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblcategory;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldescription;
    private javax.swing.JTextArea tadescription;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtcategory;
    private javax.swing.JTextField txtcomplint;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtstatus;
    // End of variables declaration//GEN-END:variables
}
